openapi: 3.0.3
info:
  title: Paypal Subscriptions Authorizations Trackers API
  description: You can use billing plans and subscriptions to create subscriptions that process recurring PayPal payments for physical or digital goods, or services. A plan includes pricing and billing cycle information that defines the amount and frequency of charge for a subscription. You can also define a fixed plan, such as a $5 basic plan or a volume- or graduated-based plan with pricing tiers based on the quantity purchased. For more information, see <a href="/docs/subscriptions/">Subscriptions Overview</a>.
  version: '1.6'
  contact: {}
servers:
- url: https://api-m.sandbox.paypal.com
  description: PayPal Sandbox Environment
- url: https://api-m.paypal.com
  description: PayPal Live Environment
tags:
- name: Trackers
  description: Use the `/trackers` resource to update and retrieve tracking information for PayPal orders.
paths:
  /v2/checkout/orders/{id}/trackers/{tracker_id}:
    patch:
      summary: Update or cancel tracking information for a PayPal order
      description: Updates or cancels the tracking information for a PayPal order, by ID. Updatable attributes or objects:<br/><br/><table><thead><th>Attribute</th><th>Op</th><th>Notes</th></thead><tbody></tr><tr><td><code>items</code></td><td>replace</td><td>Using replace op for <code>items</code> will replace the entire <code>items</code> object with the value sent in request.</td></tr><tr><td><code>notify_payer</code></td><td>replace, add</td><td></td></tr><tr><td><code>status</code></td><td>replace</td><td>Only patching status to CANCELLED is currently supported.</td></tr></tbody></table>
      operationId: orders.trackers.patch
      responses:
        '204':
          description: A successful request returns the HTTP `204 No Content` status code with an empty object in the JSON response body.
        '400':
          description: Request is not well-formed, syntactically incorrect, or violates schema.
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/error_400'
                - $ref: '#/components/schemas/orders.trackers.patch-400'
        '403':
          description: Authorization failed due to insufficient permissions.
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/error_403'
                - $ref: '#/components/schemas/orders.trackers.patch-403'
        '404':
          description: The specified resource does not exist.
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/error_404'
                - $ref: '#/components/schemas/orders.trackers.patch-404'
        '422':
          description: The requested action could not be performed, semantically incorrect, or failed business validation.
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/error_422'
                - $ref: '#/components/schemas/orders.trackers.patch-422'
        '500':
          description: An internal server error has occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_500'
        default:
          $ref: '#/components/responses/default'
      parameters:
      - $ref: '#/components/parameters/id'
      - $ref: '#/components/parameters/tracker_id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/patch_request'
            examples:
              orders_patch_request:
                value:
                - op: replace
                  path: /purchase_units/@reference_id=='PUHF'/shipping/address
                  value:
                    address_line_1: 2211 N First Street
                    address_line_2: Building 17
                    admin_area_2: San Jose
                    admin_area_1: CA
                    postal_code: '95131'
                    country_code: US
      security:
      - Oauth2:
        - https://uri.paypal.com/services/payments/payment
      tags:
      - Trackers
  /v1/shipping/trackers:
    post:
      summary: Add tracking information for PayPal transaction
      description: Adds tracking information for a PayPal transaction.
      operationId: trackers.post
      responses:
        '200':
          description: A successful request returns the HTTP 200 OK status code and a JSON response body that shows tracking information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tracker_identifier_collection'
        default:
          description: The error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      requestBody:
        $ref: '#/components/requestBodies/tracker_collection'
      security:
      - Oauth2:
        - https://uri.paypal.com/services/shipping/trackers/readwrite
      tags:
      - Trackers
    get:
      summary: Paypal List tracking information
      description: Lists tracking information that meet search criteria. The tracking ID is required but the tracking number is optional.
      operationId: trackers-batch.get
      responses:
        '200':
          description: A successful request returns the HTTP 200 OK status code and a JSON response body that lists tracking information that meets search criteria.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tracker'
        default:
          description: The error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      parameters:
      - $ref: '#/components/parameters/transaction_id'
      - $ref: '#/components/parameters/tracking_number'
      - $ref: '#/components/parameters/account_id'
      security:
      - Oauth2:
        - https://uri.paypal.com/services/shipping/trackers/read
      tags:
      - Trackers
  /v1/shipping/trackers/{id}:
    put:
      summary: Update or cancel tracking information for PayPal transaction
      description: Updates or cancels the tracking information for a PayPal transaction, by ID. To cancel tracking information, call this method and set the status to CANCELLED. For more information, see <a href="/docs/tracking/integrate/#update-or-cancel-tracking-information">Update or cancel tracking information</a>.
      operationId: trackers.put
      responses:
        '204':
          description: A successful request returns the HTTP 204 OK status code with no JSON response body.
        default:
          description: The error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      parameters:
      - $ref: '#/components/parameters/id_2'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/tracker'
      security:
      - Oauth2:
        - https://uri.paypal.com/services/shipping/trackers/readwrite
      tags:
      - Trackers
    get:
      summary: Paypal Show tracking information
      description: Shows tracking information, by tracker ID, for a PayPal transaction.
      operationId: trackers.get
      responses:
        '200':
          description: A successful request returns the HTTP `200 OK` status code and a JSON response body that shows tracking information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tracker'
        default:
          description: The error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      parameters:
      - $ref: '#/components/parameters/id_2'
      - $ref: '#/components/parameters/account_id'
      security:
      - Oauth2:
        - https://uri.paypal.com/services/shipping/trackers/read
      tags:
      - Trackers
components:
  schemas:
    error_404:
      type: object
      title: Not found Error
      description: The server has not found anything matching the request URI. This either means that the URI is incorrect or the resource is not available.
      properties:
        name:
          type: string
          enum:
          - RESOURCE_NOT_FOUND
        message:
          type: string
          enum:
          - The specified resource does not exist.
        details:
          type: array
          items:
            $ref: '#/components/schemas/error_details'
        debug_id:
          type: string
          description: The PayPal internal ID. Used for correlation purposes.
        links:
          description: An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
          type: array
          minItems: 0
          maxItems: 10000
          items:
            $ref: '#/components/schemas/error_link_description'
    tracker:
      type: object
      title: Tracker
      description: The tracking information for a shipment.
      properties:
        transaction_id:
          type: string
          description: The PayPal transaction ID.
          minLength: 1
          maxLength: 50
          pattern: ^[a-zA-Z0-9]*$
        tracking_number:
          type: string
          description: The tracking number for the shipment.
          minLength: 1
          maxLength: 64
        tracking_number_type:
          description: The type of tracking number.
          $ref: '#/components/schemas/tracking_number_type'
        status:
          $ref: '#/components/schemas/tracking_status'
        shipment_date:
          $ref: '#/components/schemas/date_no_time'
          description: The date when the shipment occurred, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
        carrier:
          $ref: '#/components/schemas/carrier'
        carrier_name_other:
          type: string
          description: The name of the carrier for the shipment. Provide this value only if the carrier parameter is OTHER.
          minLength: 1
          maxLength: 64
        postage_payment_id:
          type: string
          description: The postage payment ID.
          readOnly: true
          minLength: 1
          maxLength: 64
        notify_buyer:
          type: boolean
          description: If true , sends an email notification to the buyer of the PayPal transaction. The email contains the tracking information that was uploaded through the API.
          default: false
        quantity:
          type: integer
          description: The quantity of items shipped.
          readOnly: true
          minimum: 1
          maximum: 22
        tracking_number_validated:
          type: boolean
          description: Indicates whether the carrier validated the tracking number.
          readOnly: true
        last_updated_time:
          $ref: '#/components/schemas/date_time'
          description: The date and time when the tracking information was last updated, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6).
        shipment_direction:
          type: string
          description: To denote whether the shipment is sent forward to the receiver or returned back.
          minLength: 1
          maxLength: 50
          enum:
          - FORWARD
          - RETURN
        shipment_uploader:
          readOnly: true
          type: string
          description: To denote which party uploaded the shipment tracking info.
          minLength: 1
          maxLength: 50
          enum:
          - MERCHANT
          - CONSUMER
          - PARTNER
        account_id:
          type: string
          description: Encrypted PayPal Account ID of the buyer or seller.
          readOnly: true
          minLength: 13
          maxLength: 13
          pattern: ^[2-9A-HJ-NP-Z]{13}$
        tracking_url:
          type: string
          format: uri
          minLength: 1
          maxLength: 250
          description: Tracking Link of the shipment.
        links:
          type: array
          description: An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
          readOnly: true
          items:
            $ref: '#/components/schemas/link_description'
            readOnly: true
      required:
      - transaction_id
      - status
    tracking_status:
      type: string
      title: Tracking Status
      description: The status of the item shipment. For allowed values, see <a href="/docs/tracking/reference/shipping-status/">Shipping Statuses</a>.
      minLength: 1
      maxLength: 64
      enum:
      - CANCELLED
      - DELIVERED
      - LOCAL_PICKUP
      - ON_HOLD
      - SHIPPED
      - SHIPMENT_CREATED
      - DROPPED_OFF
      - IN_TRANSIT
      - RETURNED
      - LABEL_PRINTED
      - ERROR
      - UNCONFIRMED
      - PICKUP_FAILED
      - DELIVERY_DELAYED
      - DELIVERY_SCHEDULED
      - DELIVERY_FAILED
      - INRETURN
      - IN_PROCESS
      - NEW
      - VOID
      - PROCESSED
      - NOT_SHIPPED
      - COMPLETED
    error_409:
      type: object
      title: Resource Conflict Error
      description: The server has detected a conflict while processing this request.
      properties:
        name:
          type: string
          enum:
          - RESOURCE_CONFLICT
        message:
          type: string
          enum:
          - The server has detected a conflict while processing this request.
        details:
          type: array
          items:
            $ref: '#/components/schemas/error_details'
        debug_id:
          type: string
          description: The PayPal internal ID. Used for correlation purposes.
        links:
          description: An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
          type: array
          minItems: 0
          maxItems: 10000
          items:
            $ref: '#/components/schemas/error_link_description'
    orders.trackers.patch-422:
      properties:
        details:
          type: array
          items:
            anyOf:
            - title: INVALID_JSON_POINTER_FORMAT
              properties:
                issue:
                  type: string
                  enum:
                  - INVALID_JSON_POINTER_FORMAT
                description:
                  type: string
                  enum:
                  - Path should be a valid [JSON Pointer](https://tools.ietf.org/html/rfc6901) that references a location within the request where the operation is performed.
            - title: NOT_PATCHABLE
              properties:
                issue:
                  type: string
                  enum:
                  - NOT_PATCHABLE
                description:
                  type: string
                  enum:
                  - Cannot be patched.
            - title: PATCH_VALUE_REQUIRED
              properties:
                issue:
                  type: string
                  enum:
                  - PATCH_VALUE_REQUIRED
                description:
                  type: string
                  enum:
                  - Specify a `value` for the field being patched.
            - title: PATCH_PATH_REQUIRED
              properties:
                issue:
                  type: string
                  enum:
                  - PATCH_PATH_REQUIRED
                description:
                  type: string
                  enum:
                  - Specify a `value` for the field in which the operation needs to be performed.
            - title: ITEM_SKU_MISMATCH
              properties:
                issue:
                  type: string
                  enum:
                  - ITEM_SKU_MISMATCH
                description:
                  type: string
                  enum:
                  - Item sku must match one of the items sku that was provided during order creation.
    tracker_identifier_collection:
      type: object
      title: Tracker Identifier Collection
      description: The add tracking information for a PayPal transaction response details.
      properties:
        tracker_identifiers:
          type: array
          description: An array of tracking IDs.
          items:
            $ref: '#/components/schemas/tracker_identifier'
          minItems: 1
          maxItems: 100
        links:
          type: array
          description: An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
          readOnly: true
          items:
            $ref: '#/components/schemas/link_description'
            readOnly: true
    link_description:
      type: object
      title: Link Description
      description: A request-related [HATEOAS link](/docs/api/reference/api-responses/#hateoas-links).
      required:
      - href
      - rel
      properties:
        href:
          type: string
          description: The complete target URL. To make the related call, combine the method with this link, in [URI template format](https://tools.ietf.org/html/rfc6570). Include the `$`, `(`, and `)` characters for pre-processing. The `href` is the key HATEOAS component that links a completed call with a subsequent call.
        rel:
          type: string
          description: The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml).
        method:
          type: string
          description: The HTTP method required to make the related call.
          enum:
          - GET
          - POST
          - PUT
          - DELETE
          - HEAD
          - CONNECT
          - OPTIONS
          - PATCH
    patch:
      type: object
      title: Patch
      description: The JSON patch object to apply partial updates to resources.
      properties:
        op:
          type: string
          description: The operation.
          enum:
          - add
          - remove
          - replace
          - move
          - copy
          - test
        path:
          type: string
          description: The <a href="https://tools.ietf.org/html/rfc6901">JSON Pointer</a> to the target document location at which to complete the operation.
        value:
          title: Patch Value
          description: The value to apply. The <code>remove</code>, <code>copy</code>, and <code>move</code> operations do not require a value. Since <a href="https://www.rfc-editor.org/rfc/rfc69021">JSON Patch</a> allows any type for <code>value</code>, the <code>type</code> property is not specified.
        from:
          type: string
          description: The <a href="https://tools.ietf.org/html/rfc6901">JSON Pointer</a> to the target document location from which to move the value. Required for the <code>move</code> operation.
      required:
      - op
    date_no_time:
      type: string
      description: The stand-alone date, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). To represent special legal values, such as a date of birth, you should use dates with no associated time or time-zone data. Whenever possible, use the standard `date_time` type. This regular expression does not validate all dates. For example, February 31 is valid and nothing is known about leap years.
      format: ppaas_date_notime_v2
      minLength: 10
      maxLength: 10
      pattern: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$
    error_403:
      type: object
      title: Not Authorized Error
      description: 'The client is not authorized to access this resource, although it may have valid credentials. '
      properties:
        name:
          type: string
          enum:
          - NOT_AUTHORIZED
        message:
          type: string
          enum:
          - Authorization failed due to insufficient permissions.
        details:
          type: array
          items:
            $ref: '#/components/schemas/error_details'
        debug_id:
          type: string
          description: The PayPal internal ID. Used for correlation purposes.
        links:
          description: An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
          type: array
          minItems: 0
          maxItems: 10000
          items:
            $ref: '#/components/schemas/error_link_description'
    error_422:
      type: object
      title: Unprocessable Entity Error
      description: The requested action cannot be performed and may require interaction with APIs or processes outside of the current request. This is distinct from a 500 response in that there are no systemic problems limiting the API from performing the request.
      properties:
        name:
          type: string
          enum:
          - UNPROCESSABLE_ENTITY
        message:
          type: string
          enum:
          - The requested action could not be performed, semantically incorrect, or failed business validation.
        details:
          type: array
          items:
            $ref: '#/components/schemas/error_details'
        debug_id:
          type: string
          description: The PayPal internal ID. Used for correlation purposes.
        links:
          description: An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
          type: array
          minItems: 0
          maxItems: 10000
          items:
            $ref: '#/components/schemas/error_link_description'
    error_details:
      title: Error Details
      type: object
      description: The error details. Required for client-side `4XX` errors.
      properties:
        field:
          type: string
          description: The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors.
        value:
          type: string
          description: The value of the field that caused the error.
        location:
          $ref: '#/components/schemas/error_location'
        issue:
          type: string
          description: The unique, fine-grained application-level error code.
        description:
          type: string
          description: The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value.
      required:
      - issue
    tracker_identifier:
      type: object
      title: Tracking Identifier
      description: The tracking identifiers for a shipment.
      properties:
        transaction_id:
          type: string
          description: The PayPal transaction ID.
          minLength: 1
          maxLength: 50
          pattern: ^[a-zA-Z0-9]*$
        tracking_number:
          type: string
          description: The tracking number for the shipment.
          minLength: 1
          maxLength: 64
        links:
          type: array
          description: An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
          readOnly: true
          items:
            $ref: '#/components/schemas/link_description'
            readOnly: true
      required:
      - transaction_id
    error_link_description:
      title: Link Description
      description: The request-related [HATEOAS link](/api/rest/responses/#hateoas-links) information.
      type: object
      required:
      - href
      - rel
      properties:
        href:
          description: The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call.
          type: string
          minLength: 0
          maxLength: 20000
          pattern: ^.*$
        rel:
          description: The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml).
          type: string
          minLength: 0
          maxLength: 100
          pattern: ^.*$
        method:
          description: The HTTP method required to make the related call.
          type: string
          minLength: 3
          maxLength: 6
          pattern: ^[A-Z]*$
          enum:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
    tracking_number_type:
      type: string
      title: Tracking Number Type
      description: The tracking number type.
      minLength: 1
      maxLength: 64
      enum:
      - CARRIER_PROVIDED
      - E2E_PARTNER_PROVIDED
    error_default:
      description: The default error response.
      oneOf:
      - $ref: '#/components/schemas/error_400'
      - $ref: '#/components/schemas/error_401'
      - $ref: '#/components/schemas/error_403'
      - $ref: '#/components/schemas/error_404'
      - $ref: '#/components/schemas/error_409'
      - $ref: '#/components/schemas/error_415'
      - $ref: '#/components/schemas/error_422'
      - $ref: '#/components/schemas/error_500'
      - $ref: '#/components/schemas/error_503'
    error_location:
      type: string
      description: The location of the field that caused the error. Value is `body`, `path`, or `query`.
      enum:
      - body
      - path
      - query
      default: body
    patch_request:
      type: array
      title: Patch Request
      description: An array of JSON patch objects to apply partial updates to resources.
      items:
        $ref: '#/components/schemas/patch'
    link_description-2:
      type: object
      title: Link Description
      description: The request-related [HATEOAS link](/docs/api/reference/api-responses/#hateoas-links) information.
      required:
      - href
      - rel
      properties:
        href:
          type: string
          description: The complete target URL. To make the related call, combine the method with this [URI Template-formatted](https://tools.ietf.org/html/rfc6570) link. For pre-processing, include the `$`, `(`, and `)` characters. The `href` is the key HATEOAS component that links a completed call with a subsequent call.
        rel:
          type: string
          description: The [link relation type](https://tools.ietf.org/html/rfc5988#section-4), which serves as an ID for a link that unambiguously describes the semantics of the link. See [Link Relations](https://www.iana.org/assignments/link-relations/link-relations.xhtml).
        method:
          type: string
          description: The HTTP method required to make the related call.
          enum:
          - GET
          - POST
          - PUT
          - DELETE
          - HEAD
          - CONNECT
          - OPTIONS
          - PATCH
    orders.trackers.patch-403:
      properties:
        details:
          type: array
          items:
            anyOf:
            - title: PERMISSION_DENIED
              properties:
                issue:
                  type: string
                  enum:
                  - PERMISSION_DENIED
                description:
                  type: string
                  enum:
                  - You do not have permission to access or perform operations on this resource.
    error:
      type: object
      title: Error
      description: The error details.
      properties:
        name:
          type: string
          description: The human-readable, unique name of the error.
        message:
          type: string
          description: The message that describes the error.
        debug_id:
          type: string
          description: The PayPal internal ID. Used for correlation purposes.
        information_link:
          type: string
          description: The information link, or URI, that shows detailed information about this error for the developer.
          readOnly: true
        details:
          type: array
          description: An array of additional details about the error.
          items:
            $ref: '#/components/schemas/error_details-2'
        links:
          type: array
          description: An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
          readOnly: true
          items:
            $ref: '#/components/schemas/link_description-2'
            readOnly: true
      required:
      - name
      - message
      - debug_id
    error_503:
      type: object
      title: Service Unavailable Error
      description: The server is temporarily unable to handle the request, for example, because of planned maintenance or downtime.
      properties:
        name:
          type: string
          enum:
          - SERVICE_UNAVAILABLE
        message:
          type: string
          enum:
          - Service Unavailable.
        debug_id:
          type: string
          description: The PayPal internal ID. Used for correlation purposes.
        links:
          description: An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
          type: array
          minItems: 0
          maxItems: 10000
          items:
            $ref: '#/components/schemas/error_link_description'
      example:
        name: SERVICE_UNAVAILABLE
        message: Service Unavailable.
        debug_id: 90957fca61718
        information_link: https://developer.paypal.com/docs/api/orders/v2/#error-SERVICE_UNAVAILABLE
    error_400:
      type: object
      title: Bad Request Error
      description: Request is not well-formed, syntactically incorrect, or violates schema.
      properties:
        name:
          type: string
          enum:
          - INVALID_REQUEST
        message:
          type: string
          enum:
          - Request is not well-formed, syntactically incorrect, or violates schema.
        details:
          type: array
          items:
            $ref: '#/components/schemas/error_details'
        debug_id:
          type: string
          description: The PayPal internal ID. Used for correlation purposes.
        links:
          description: An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
          type: array
          minItems: 0
          maxItems: 10000
          items:
            $ref: '#/components/schemas/error_link_description'
    orders.trackers.patch-400:
      properties:
        details:
          type: array
          items:
            anyOf:
            - title: FIELD_NOT_PATCHABLE
              properties:
                issue:
                  type: string
                  enum:
                  - FIELD_NOT_PATCHABLE
                description:
                  type: string
                  enum:
                  - Field cannot be patched.
            - title: INVALID_PARAMETER_VALUE
              properties:
                issue:
                  type: string
                  enum:
                  - INVALID_PARAMETER_VALUE
                description:
                  type: string
                  enum:
                  - The value of a field is invalid.
            - title: MISSING_REQUIRED_PARAMETER
              properties:
                issue:
                  type: string
                  enum:
                  - MISSING_REQUIRED_PARAMETER
                description:
                  type: string
                  enum:
                  - A required field or parameter is missing.
            - title: INVALID_STRING_LENGTH
              properties:
                issue:
                  type: string
                  enum:
                  - INVALID_STRING_LENGTH
                description:
                  type: string
                  enum:
                  - The value of a field is either too short or too long.
            - title: INVALID_PATCH_OPERATION
              properties:
                issue:
                  type: string
                  enum:
                  - INVALID_PATCH_OPERATION
                description:
                  type: string
                  enum:
                  - The operation cannot be honored. Cannot add a property that's already present, use replace. Cannot remove a property thats not present, use add. Cannot replace a property thats not present, use add.
            - title: MALFORMED_REQUEST_JSON
              properties:
                issue:
                  type: string
                  enum:
                  - MALFORMED_REQUEST_JSON
                description:
                  type: string
                  enum:
                  - The request JSON is not well formed.
    error_details-2:
      title: Error Details
      type: object
      description: The error details. Required for client-side `4XX` errors.
      properties:
        field:
          type: string
          description: The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors.
        value:
          type: string
          description: The value of the field that caused the error.
        location:
          type: string
          description: The location of the field that caused the error. Value is `body`, `path`, or `query`.
          default: body
        issue:
          type: string
          description: The unique, fine-grained application-level error code.
        description:
          type: string
          description: The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value.
      required:
      - issue
    error_401:
      type: object
      title: Unauthorized Error
      description: Authentication failed due to missing Authorization header, or invalid authentication credentials.
      properties:
        name:
          type: string
          enum:
          - AUTHENTICATION_FAILURE
        message:
          type: string
          enum:
          - Authentication failed due to missing authorization header, or invalid authentication credentials.
        details:
          type: array
          items:
            $ref: '#/components/schemas/error_details'
        debug_id:
          type: string
          description: The PayPal internal ID. Used for correlation purposes.
        links:
          description: An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
          type: array
          minItems: 0
          maxItems: 10000
          items:
            $ref: '#/components/schemas/error_link_description'
    tracker_collection:
      type: object
      title: Tracker Collection
      description: The add tracking information for one or more transactions response details.
      properties:
        trackers:
          type: array
          description: An array of tracking information for shipments.
          items:
            $ref: '#/components/schemas/tracker'
          minItems: 1
          maxItems: 20
        links:
          type: array
          description: An array of request-related [HATEOAS links](/docs/api/reference/api-responses/#hateoas-links).
          readOnly: true
          items:
            $ref: '#/components/schemas/link_description'
            readOnly: true
    error_415:
      type: object
      title: Unsupported Media Type Error
      description: The server does not support the request payload's media type.
      properties:
        name:
          type: string
          enum:
          - UNSUPPORTED_MEDIA_TYPE
        message:
          type: string
          enum:
          - The server does not support the request payload's media type.
        details:
          type: array
          items:
            $ref: '#/components/schemas/error_details'
        debug_id:
          type: string
          description: The PayPal internal ID. Used for correlation purposes.
        links:
          description: An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
          type: array
          minItems: 0
          maxItems: 10000
          items:
            $ref: '#/components/schemas/error_link_description'
    orders.trackers.patch-404:
      properties:
        details:
          type: array
          items:
            anyOf:
            - title: TRACKER_ID_NOT_FOUND
              properties:
                issue:
                  type: string
                  enum:
                  - TRACKER_ID_NOT_FOUND
                description:
                  type: string
                  enum:
                  - Specified tracker ID does not exist. Check the tracker ID and try again.
    error_500:
      type: object
      title: Internal Server Error
      description: This is either a system or application error, and generally indicates that although the client appeared to provide a correct request, something unexpected has gone wrong on the server.
      properties:
        name:
          type: string
          enum:
          - INTERNAL_SERVER_ERROR
        message:
          type: string
          enum:
          - An internal server error occurred.
        debug_id:
          type: string
          description: The PayPal internal ID. Used for correlation purposes.
        links:
          description: An array of request-related [HATEOAS links](https://en.wikipedia.org/wiki/HATEOAS).
          type: array
          minItems: 0
          maxItems: 10000
          items:
            $ref: '#/components/schemas/error_link_description'
      example:
        name: INTERNAL_SERVER_ERROR
        message: An internal server error occurred.
        debug_id: 90957fca61718
        links:
        - href: https://developer.paypal.com/api/orders/v2/#error-INTERNAL_SERVER_ERROR
          rel: information_link
    date_time:
      type: string
      description: The date and time, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). Seconds are required while fractional seconds are optional.<blockquote><strong>Note:</strong> The regular expression provides guidance but does not reject all invalid dates.</blockquote>
      format: ppaas_date_time_v3
      minLength: 20
      maxLength: 64
      pattern: ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])[T,t]([0-1][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)([.][0-9]+)?([Zz]|[+-][0-9]{2}:[0-9]{2})$
    carrier:
      type: string
      title: Carrier
      description: The carrier for the shipment. Some carriers have a global version as well as local subsidiaries. The subsidiaries are repeated over many countries and might also have an entry in the global list. Choose the carrier for your country. If the carrier is not available for your country, choose the global version of the carrier. If your carrier name is not in the list, set `carrier` to `OTHER` and set carrier name in `carrier_name_other`. For allowed values, see <a href="/docs/tracking/reference/carriers/">Carriers</a>.
      minLength: 1
      maxLength: 64
      enum:
      - 2EBOX
      - 360LION
      - 3JMSLOGISTICS
      - '4_72'
      - 6LS
      - A1POST
      - AAA_COOPER
      - ABCUSTOM
      - ABXEXPRESS_MY
      - ACOMMMERCE
      - ACSWORLDWIDE
      - ACS_GR
      - ADERONLINE
      - ADICIONAL
      - ADSONE
      - ADUIEPYLE
      - AERONET
      - AEX
      - AFLLOG_FTP
      - AGILITY
      - AIRMEE_WEBHOOK
      - AIR_CANADA_GLOBAL
      - ALFATREX
      - ALLIEDEXPRESS
      - ALLJOY
      - ALPHAFAST
      - ALWAYS_EXPRESS
      - AMAZON
      - AMAZON_FBA_SWISHIP
      - AMAZON_SHIP_MCF
      - AMSTAN
      - AMS_GRP
      - ANDREANI
      - ANICAM_BOX
      - ANJUN
      - ANSERX
      - AN_POST
      - AO_COURIER
      - AO_DEUTSCHLAND
      - APC_OVERNIGHT
      - APC_OVERNIGHT_CONNUM
      - APG
      - APRISAEXPRESS
      - AQUILINE
      - ARAMEX
      - ARAMEX_AU
      - ARCO_SPEDIZIONI
      - ARE_EMIRATES_POST
      - ARG_OCA
      - ARK_LOGISTICS
      - ASE
      - ASENDIA_HK
      - ASENDIA_UK
      - ASENDIA_USA
      - ASIGNA
      - AUPOST_CN
      - AUSTRIAN_POST_EXPRESS
      - AUS_STARTRACK
      - AUS_TOLL
      - AU_AUSTRIAN_POST
      - AU_AU_POST
      - AU_TNT
      - AVERITT
      - BEL_DHL
      - BEL_RS
      - BESTWAYPARCEL
      - BE_BPOST
      - BE_KIALA
      - BG_BULGARIAN_POST
      - BH_POSTA
      - BH_WORLDWIDE
      - BIRDSYSTEM
      - BJSHOMEDELIVERY
      - BLINKLASTMILE
      - BLR_BELPOST
      - BLUECARE
      - BLUESTAR
      - BLUEX
      - BNEED
      - BOMBINOEXP
      - BOND
      - BONDSCOURIERS
      - BORDEREXPRESS
      - BOX_BERRY
      - BPOST_INT
      - BRA_CORREIOS
      - BRING
      - BROUWER_TRANSPORT
      - BRT_IT
      - BRT_IT_PARCELID
      - BRT_IT_SENDER_REF
      - BUDBEE_WEBHOOK
      - BUYLOGIC
      - B_TWO_C_EUROPE
      - CAE_DELIVERS
      - CAINIAO
      - CARIBOU
      - CARRIERS
      - CARRY_FLAP
      - CA_CANADA_POST
      - CA_CANPAR
      - CA_GREYHOUND
      - CA_PUROLATOR
      - CBL_LOGISTICA
      - CDEK
      - CDEK_TR
      - CELERITAS
      - CELLO_SQUARE
      - CESKA_CZ
      - CEVA
      - CFL_LOGISTICS
      - CGS_EXPRESS
      - CHAMPION_LOGISTICS
      - CHITCHATS
      - CHOIR_EXP
      - CHROBINSON
      - CHRONOPOST_FR
      - CHUKOU1
      - CH_SWISS_POST_PRIORITY
      - CITYLINK_MY
      - CJPACKET
      - CJ_CENTURY
      - CJ_GLS
      - CJ_HK_INTERNATIONAL
      - CJ_INT_MY
      - CJ_KR
      - CJ_LOGISTICS
      - CJ_TH
      - CLEVY_LINKS
      - CLE_LOGISTICS
      - CLOUDWISH_ASIA
      - CNDEXPRESS
      - CNEXPS
      - CNWANGTONG
      - CN_17POST
      - CN_BESTEXPRESS
      - CN_BOXC
      - CN_CHINA_POST_EMS
      - CN_DPEX
      - CN_EMS
      - CN_EQUICK
      - CN_GOFLY
      - CN_JCEX
      - CN_PAYPAL_PACKAGE
      - CN_POST56
      - CN_SF_EXPRESS
      - CN_STO
      - CN_WEDO
      - CN_WISHPOST
      - CN_YUNDA
      - COLIS_PRIVE
      - COLLECTCO
      - COLLIVERY
      - COMET_TECH
      - CONTINENTAL
      - CON_WAY
      - COORDINADORA
      - COPA_COURIER
      - COPE
      - CORPORATECOURIERS_WEBHOOK
      - CORREOS_DE_MEXICO
      - CORREOS_ES
      - CORREOS_EXPRESS
      - CORREO_UY
      - COSTMETICSNOW
      - COURANT_PLUS
      - COUREX
      - COURIERS_PLEASE
      - CPACKET
      - CPEX
      - CROSHOT
      - CSE
      - CTC_EXPRESS
      - CUBYN
      - CUCKOOEXPRESS
      - CYPRUS_POST_CYP
      - DAIGLOBALTRACK
      - DAJIN
      - DANSKE_FRAGT
      - DAWN_WING
      - DAYTON_FREIGHT
      - DBSCHENKER_B2B
      - DBSCHENKER_SE
      - DBSCHENKER_SV
      - DDEXPRESS
      - DEALERSEND
      - DELIVERYONTIME
      - DELNEXT
      - DELTEC_UK
      - DEMANDSHIP
      - DESCARTES
      - DESIGNERTRANSPORT_WEBHOOK
      - DESTINY
      - DEX_I
      - DE_ASENDIA
      - DE_DEUTSCHE
      - DE_DEUTSCHE_POST_DHL_WITHIN_EUROPE_TRACKNET
      - DE_DHL_EXPRESS
      - DE_DPD_DELISTRACK
      - DE_GLS
      - DHL
      - DHL_ACTIVE_TRACING
      - DHL_AU
      - DHL_BENELUX
      - DHL_ECOMERCE_ASA
      - DHL_ES
      - DHL_FR
      - DHL_FREIGHT
      - DHL_GLOBAL_MAIL_ASIA
      - DHL_HK
      - DHL_JP
      - DHL_PARCEL_ES
      - DHL_PARCEL_NL
      - DHL_PARCEL_RU
      - DHL_PL
      - DHL_REFR
      - DHL_SG
      - DHL_SUPPLY_CHAIN
      - DHL_UK
      - DIAMOND_EUROGISTICS
      - DICOM
      - DIDADI
      - DIMERCO
      - DIRECTCOURIERS
      - DIRECTLOG
      - DIRECTPARCELS
      - DMM_NETWORK
      - DMS_MATRIX
      - DOBROPOST
      - DOORA
      - DOORDASH_WEBHOOK
      - DPD
      - DPD_DELISTRACK
      - DPD_FR
      - DPD_HGRY
      - DPD_HK
      - DPD_IR
      - DPD_LOCAL
      - DPD_LOCAL_REF
      - DPD_POLAND
      - DPD_RO
      - DPD_RU
      - DPEX
      - DPE_EXPRESS
      - DPE_SOUTH_AFRC
      - DSV
      - DTDC_AU
      - DTDC_EXPRESS
      - DTDC_IN
      - DTD_EXPR
      - DX_SFTP
      - DYLT
      - DYNALOGIC
      - EASY_MAIL
      - ECEXPRESS
      - ECHO
      - ECMS
      - ECOSCOOTING
      - EFEX
      - EFS
      - EKART
      - ELIAN_POST
      - EMPS_CN
      - ENDEAVOUR_DELIVERY
      - ENVIALIA_REFERENCE
      - EPARCEL_KR
      - EPST_GLBL
      - EP_BOX
      - ESHIPPING
      - ESP_ASM
      - ESP_ENVIALIA
      - ESP_MRW
      - ESP_NACEX
      - ESP_PACKLINK
      - ESP_REDUR
      - ETOMARS
      - ETOTAL
      - ETS_EXPRESS
      - EU_FLEET_SOLUTIONS
      - EU_IMX
      - EXPRESSSALE
      - EZSHIP
      - FARGOOD
      - FAR_INTERNATIONAL
      - FASTRACK
      - FASTRK_SERV
      - FASTWAY_IR
      - FASTWAY_NZ
      - FDSEXPRESS
      - FEDEX
      - FEDEX_CROSSBORDER
      - FEDEX_FR
      - FEDEX_INTL_MLSERV
      - FEDEX_POLAND
      - FEDEX_UK
      - FETCHR_WEBHOOK
      - FIEGE
      - FIEGE_NL
      - FIRSTMILE
      - FLASHEXPRESS
      - FMX
      - FONSEN
      - FORRUN
      - FREIGHTQUOTE
      - FRETERAPIDO
      - FR_BERT
      - FR_COLIS
      - FR_EXAPAQ
      - FR_GEODIS
      - FR_GLS
      - FULFILLA
      - FULFILLME
      - FURDECO
      - GAC
      - GANGBAO
      - GBA
      - GBS_BROKER
      - GB_APC
      - GB_ARROW
      - GB_NORSK
      - GB_PANTHER
      - GB_TUFFNELLS
      - GEIS
      - GEL_EXPRESS
      - GEMWORLDWIDE
      - GENERAL_OVERNIGHT
      - GENIKI_GR
      - GEODIS_ESPACE
      - GESWL
      - GIAO_HANG
      - GIO_EXPRESS
      - GLOBALTRANZ
      - GLOBAL_ABF
      - GLOBAL_ESTES
      - GLOBAL_EXPRESS
      - GLOBAL_IPARCEL
      - GLOBAL_TNT
      - GLOBAVEND
      - GLS_CROTIA
      - GLS_CZ
      - GLS_IT
      - GLS_ITALY
      - GLS_SLOV
      - GLS_SLOVEN
      - GOGLOBALPOST
      - GOJEK
      - GRAB_WEBHOOK
      - GRUPO
      - GR_ELTA
      - GSI_EXPRESS
      - GSO
      - HAPPY2POINT
      - HCT_LOGISTICS
      - HDB
      - HDB_BOX
      - HELLMANN
      - HELTHJEM
      - HEPPNER
      - HEPPNER_FR
      - HERMES
      - HERMES_2MANN_HANDLING
      - HERMES_DE
      - HH_EXP
      - HIPSHIPPER
      - HKD
      - HK_FLYT_EXPRESS
      - HK_FOUR_PX_EXPRESS
      - HK_POST
      - HK_TGX
      - HOLISOL
      - HOME_DELIVERY_SOLUTIONS
      - HOUNDEXPRESS
      - HRPARCEL
      - HRV_HRVATSKA
      - HUAHAN_EXPRESS
      - HUNTER_EXPRESS
      - HUODULL
      - HX_EXPRESS
      - IBEONE
      - ICUMULUS
      - IDEXPRESS
      - IDN_JNE
      - IDN_LION_PARCEL
      - IDN_PANDU
      - IML
      - INDOPAKET
      - IND_BLUEDART
      - IND_DELHIVERY
      - IND_DELIVREE
      - IND_DOTZOT
      - IND_ECOM
      - IND_FIRSTFLIGHT
      - IND_GATI
      - IND_GOJAVAS
      - IND_JAYONEXPRESS
      - IND_PROFESSIONAL_COURIERS
      - IND_SAFEEXPRESS
      - IND_XPRESSBEES
      - INPOST_PACZKOMATY
      - INTEGRA2_FTP
      - INTELIPOST
      - INTEL_VALLEY
      - INTERPARCEL_AU
      - INTERPARCEL_NZ
      - INTERPARCEL_UK
      - INTEXPRESS
      - ISRAEL_POST
      - ISR_POST_DOMESTIC
      - IT_DHL_ECOMMERCE
      - IT_FERCAM
      - IT_NEXIVE
      - IT_POSTE_ITALIA
      - IT_TNT
      - IVOY_WEBHOOK
      - I_DIKA
      - JANCO
      - JANIO
      - JERSEY_POST
      - JET_SHIP
      - JINDOUYUN
      - JINSUNG
      - JOCOM
      - JOOM_LOGIS
      - JOYING_BOX
      - JPN_JAPAN_POST
      - JPN_SAGAWA
      - JP_KURO_NEKO_YAMATO_UNYUU
      - JS_EXPRESS
      - JTEXPRESS
      - JTEXPRESS_VN
      - JX
      - J_NET
      - K1_EXPRESS
      - KANGAROO_MY
      - KEC
      - KERRYTJ
      - KERRYTTC_VN
      - KERRY_ECOMMERCE
      - KGMHUB
      - KHM_CAMBODIA_POST
      - KOR_ECARGO
      - KPOST
      - KR_KOREA_POST
      - KUEHNE
      - KURASI
      - KWE_GLOBAL
      - KWT
      - KYUNGDONG_PARCEL
      - KY_EXPRESS
      - LALAMOVE
      - LANDMARK_GLOBAL
      - LANDMARK_GLOBAL_REFERENCE
      - LAO_POST
      - LATVIJAS_PASTS
      - LA_POSTE_SUIVI
      - LBCEXPRESS_FTP
      - LEADER
      - LEGION_EXPRESS
      - LEXSHIP
      - LHT_EXPRESS
      - LICCARDI_EXPRESS
      - LIEFERY
      - LINE
      - LINKBRIDGE
      - LOCUS_WEBHOOK
      - LOGISTERS
      - LOGISTICSWORLDWIDE_HK
      - LOGISTIKA
      - LOGISTYX_TRANSGROUP
      - LONESTAR
      - LOOMIS_EXPRESS
      - LOTTE
      - LTIANEXP
      - LTL
      - LTU_LIETUVOS
      - MAGYAR_HU
      - MAILAMERICAS
      - MAILPLUS_JPN
      - MAIL_PLUS
      - MAINFREIGHT
      - MAINWAY
      - MARA_XPRESS
      - MATDESPATCH
      - MATKAHUOLTO
      - MBW
      - MEX_AEROFLASH
      - MEX_ESTAFETA
      - MEX_REDPACK
      - MEX_SENDA
      - MGLOBAL
      - MIKROPAKKET
      - MIKROPAKKET_BE
      - MILKMAN
      - MORE_LINK
      - MORNING_EXPRESS
      - MRW_FTP
      - MXE
      - MX_CARGO
      - MYHERMES
      - MYS_AIRPAK
      - MYS_EMS
      - MYS_GDEX
      - MYS_MYPOST_ONLINE
      - MYS_MYS_POST
      - MYS_SKYNET
      - M_XPRESS
      - NACEX
      - NACEX_ES
      - NANJINGWOYUAN
      - NATIONAL_SAMEDAY
      - NATIONEX
      - NATIONWIDE_MY
      - NEWAY
      - NEWEGGEXPRESS
      - NEWGISTICS
      - NEWZEALAND_COURIERS
      - NG_COURIERPLUS
      - NHANS_SOLUTIONS
      - NIM_EXPRESS
      - NINJAVAN_ID
      - NINJAVAN_MY
      - NINJAVAN_SG
      - NINJAVAN_THAI
      - NINJAVAN_WB
      - NIPOST_NG
      - NLD_DHL
      - NLD_GLS
      - NLD_POSTNL
      - NLD_TRANSMISSION
      - NOVA_POSHTA
      - NOVA_POSHTA_INT
      - NOX_NACHTEXPRESS
      - NOX_NIGHT_TIME_EXPRESS
      - NTLOGISTICS_VN
      - NZ_COURIER_POST
      - NZ_NZ_POST
      - OCS
      - OCS_WORLDWIDE
      - OKAYPARCEL
      - OMNIPARCEL
      - OMNIVA
      - ONECLICK
      - ONEWORLDEXPRESS
      - ORANGE_DS
      - OSM_WORLDWIDE
      - OVERSE_EXP
      - P2P_TRC
      - PAACK_WEBHOOK
      - PADTF
      - PAGO
      - PALEXPRESS
      - PALLETWAYS
      - PALLET_NETWORK
      - PANTHER_REFERENCE
      - PAN_ASIA
      - PAPERFLY
      - PAPER_EXPRESS
      - PAQUETEXPRESS
      - PARCEL2GO
      - PARCELINKLOGISTICS
      - PARCELLED_IN
      - PARCELONE
      - PARCELPAL_WEBHOOK
      - PARCELPOINT
      - PARCELPOST_SG
      - PARCEL_2_POST
      - PARKNPARCEL
      - PCFCORP
      - PFCEXPRESS
      - PFLOGISTICS
      - PHL_AIR21
      - PHL_AIRSPEED
      - PHL_JAMEXPRESS
      - PICKRR
      - PICKUP
      - PICKUPP_MYS
      - PICKUPP_SGP
      - PILOT_FREIGHT
      - PIL_LOGISTICS
      - PITNEY_BOWES
      - PITTOHIO
      - PIXSELL
      - PLANZER
      - PLUS_LOG_UK
      - PL_POCZTA_POLSKA
      - POL_SIODEMKA
      - PONY_EXPRESS
      - POSTA_PLUS
      - POSTA_RO
      - POSTA_UKR
      - POSTEN_NORGE
      - POSTI
      - POSTNL_INTL_3S
      - POSTNL_INT_3_S
      - POSTNORD_LOGISTICS
      - POSTNORD_LOGISTICS_DK
      - POSTUR_IS
      - POST_SERBIA
      - POST_SLOVENIA
      - PRESIDENT_TRANS
      - PRESSIODE
      - PRIMAMULTICIPTA
      - PROMEDDELIVERY
      - PRT_CHRONOPOST
      - PRT_CTT
      - PRT_INT_SEUR
      - PRT_SEUR
      - PTS
      - PTT_POST
      - QUANTIUM
      - QWINTRY
      - RABEN_GROUP
      - RAF_PH
      - RAIDEREX
      - RAM
      - RCL
      - RINCOS
      - RL_US
      - ROADBULL
      - ROADRUNNER_FREIGHT
      - ROCKET_PARCEL
      - ROUTIFIC_WEBHOOK
      - ROYAL_MAIL
      - RPD2MAN
      - RPX
      - RPXLOGISTICS
      - RPX_ID
      - RUSSIAN_POST
      - RUSTON
      - RZYEXPRESS
      - SAIA_FREIGHT
      - SAILPOST
      - SAP_EXPRESS
      - SAU_SAUDI_POST
      - SCUDEX_EXPRESS
      - SDA_IT
      - SDH_SCM
      - SEFL
      - SEINO
      - SEKOLOGISTICS
      - SEKO_SFTP
      - SENDING
      - SENDIT
      - SENDLE
      - SEUR_ES
      - SEUR_SP_API
      - SFB2C
      - SFCSERVICE
      - SFC_LOGISTICS
      - SFPLUS_WEBHOOK
      - SF_EX
      - SG_DETRACK
      - SG_QXPRESS
      - SG_SG_POST
      - SG_SPEEDPOST
      - SG_TAQBIN
      - SHENZHEN
      - SHIPENTEGRA
      - SHIPPIT
      - SHIPTER
      - SHIPTOR
      - SHIP_GATE
      - SHIP_IT_ASIA
      - SHOPFANS
      - SHREENANDANCOURIER
      - SHREETIRUPATI
      - SHREE_ANJANI_COURIER
      - SHREE_MARUTI
      - SIMPLYPOST
      - SINOTRANS
      - SIN_GLBL
      - SKYBOX
      - SKYNET_UAE
      - SKYNET_UK
      - SKYNET_WORLDWIDE
      - SKYNET_ZA
      - SKY_POSTAL
      - SK_POSTA
      - SMG_EXPRESS
      - SMOOTH
      - SMSA_EXPRESS
      - SONICTL
      - SOUTH_AFRICAN_POST_OFFICE
      - SPEEDCOURIERS_GR
      - SPEEDEE
      - SPEEDEXCOURIER
      - SPOTON
      - SPRING_GDS
      - SRE_KOREA
      - STALLIONEXPRESS
      - STARKEN
      - STAR_TRACK_EXPRESS
      - STAR_TRACK_NEXT_FLIGHT
      - STEPFORWARDFS
      - STONE3PL
      - STRECK_TRANSPORT
      - SUTTON
      - SWE_POSTNORD
      - SWISHIP_DE
      - SWISS_POST_FTP
      - SYPOST
      - SZENDEX
      - TAQBIN_HK
      - TAQBIN_MY
      - TARRIVE
      - TAZMANIAN_FREIGHT
      - TCK_EXPRESS
      - TCS
      - TFM
      - TFORCE_FINALMILE
      - THABIT_LOGISTICS
      - THA_DYNAMIC_LOGISTICS
      - THA_KERRY
      - THA_THAILAND_POST
      - THECOURIERGUY
      - THEDELIVERYGROUP
      - THENILE_WEBHOOK
      - TIGFREIGHT
      - TIKI_ID
      - TIPSA
      - TNT
      - TNT_CLICK_IT
      - TNT_FR
      - TNT_NL
      - TNT_REFR
      - TNT_UK
      - TNT_UK_REFR
      - TOLL
      - TOLL_NZ
      - TOLOS
      - TOPHATTEREXPRESS
      - TOPYOU
      - TOTAL_EXPRESS
      - TOURLINE
      - TRACKON
      - TRANS_KARGO
      - TRUMPCARD
      - TRUNKRS_WEBHOOK
      - TUFFNELLS_REFERENCE
      - TWO_GO
      - TW_TAIWAN_POST
      - UBI_LOGISTICS
      - UC_EXPRE
      - UDS
      - UK_COLLECTPLUS
      - UK_DPD
      - UK_NIGHTLINE
      - UK_PARCELFORCE
      - UK_UK_MAIL
      - UK_XDP
      - UK_YODEL
      - UPS
      - UPS_FREIGHT
      - UPS_MAIL_INNOVATIONS
      - UPS_REFERENCE
      - USF_REDDAWAY
      - USHIP
      - USPS
      - US_ENSENDA
      - US_GLOBEGISTICS
      - US_LASERSHIP
      - US_OLD_DOMINION
      - US_ONTRAC
      - US_YRC
      - VAMOX
      - VENIPAK
      - VIAEUROPE
      - VIA_EXPRESS
      - VIRTRANSPORT
      - VIWO
      - VNM_VIETNAM_POST
      - VNM_VIETTELPOST
      - WAHANA_ID
      - WANBEXPRESS
      - WEASHIP
      - WEPOST
      - WESTBANK_COURIER
      - WESTGATE_GL
      - WHISTL
      - WINIT
      - WISELOADS
      - WISE_EXPRESS
      - WIZMO
      - WMG
      - WNDIRECT
      - WYNGS
      - XDE_WEBHOOK
      - XDP_UK_REFERENCE
      - XL_EXPRESS
      - XPERT_DELIVERY
      - XPOST
      - XPO_LOGISTICS
      - XPRESSEN_DK
      - XQ_EXPRESS
      - YAKIT
      - YANWEN
      - YDH_EXPRESS
      - YINGNUO_LOGISTICS
      - YODEL_DIR
      - YODEL_INTNL
      - YTO
      - YUNEXPRESS
      - YURTICI_KARGO
      - YUSEN
      - ZAJIL_EXPRESS
      - ZA_COURIERIT
      - ZA_FASTWAY
      - ZA_SPECIALISED_FREIGHT
      - ZEEK_2_DOOR
      - ZELERIS
      - ZEPTO_EXPRESS
      - ZES_EXPRESS
      - ZIINGFINALMILE
      - ZINC
      - ZJS_EXPRESS
      - ZTO_EXPRESS
      - ZYLLEM
  parameters:
    account_id:
      name: account_id
      in: query
      description: Encrypted PayPal Account ID of the buyer or seller.
      required: false
      schema:
        type: string
        minLength: 13
        maxLength: 13
        pattern: ^[2-9A-HJ-NP-Z]{13}$
    tracking_number:
      name: tracking_number
      in: query
      description: Filters the tracking information that appears in the response by a tracking number.
      required: false
      schema:
        type: string
    tracker_id:
      name: tracker_id
      in: path
      description: The order tracking ID.
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 36
        pattern: ^[A-Z0-9]+$
    id_2:
      name: id
      in: path
      description: The ID of the tracker in the <code><var>transaction_id</var>-<var>tracking_number</var></code> format.
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 100
        pattern: ^[a-zA-Z0-9-_]*$
    id:
      name: id
      in: path
      description: The ID of the order that the tracking information is associated with.
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 36
        pattern: ^[A-Z0-9]+$
    transaction_id:
      name: transaction_id
      in: query
      description: Filters the tracking information that appears in the response by a PayPal transaction ID.
      required: true
      schema:
        type: string
  requestBodies:
    tracker_collection:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/tracker_collection'
  responses:
    default:
      description: The default response.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error_default'
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 authentication
      flows:
        clientCredentials:
          tokenUrl: /v1/oauth2/token
          scopes:
            https://uri.paypal.com/services/subscriptions: Manage plan & subscription
externalDocs:
  url: https://developer.paypal.com/docs/api/subscriptions/v1/
